spring:
  application:
    name: api
  profiles:
    include:
      - domain
      - common
      - infra
    active: dev

  security:
    user:
      name: user
      password: 1234
swagger:
  user: ${SWAGGER_USER}
  password: ${SWAGGER_PASSWORD}


---
spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: test

