spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(umIPYOdrigHivpZxQUaBn+1360z+xy13Hb4gHcoDY16JKXGxOF2jx4F+KkoFv9RKiIu7nXxn7tv/PoUCRVEYxqf96mTuqV007F1N8C45mpzyBg+tCBbRyNW66k7k4E0o)
    username: ENC(gh46WFclECYl96UilXt8Lw==)
    password: ENC(2HaAZ8j7cAaYFkIcemnUifSA0UAtPFLt)

  security:
    user:
      name: user
      password: 1234
    oauth2:
      client:
        id: 924373234165-adalqufkonkljl23qk6vv4g3bnc9imfr.apps.googleusercontent.com


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: celebit-sluv-mvp2

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  header: Authorization
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
  expiration-seconds: 864000

apple:
#  nonce: 1
  clientId: Sluv.sluv-ios-renew
  openKey: https://appleid.apple.com/auth/keys
  iss: https://appleid.apple.com
