spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(lsltGEIQDlOE6V2w2GsIOVBsb5nbKK12FjwU+GTbqEGI7RXa590K5ZkPKpLEMYcFklyubaxtYjDo4rKdYw4P4w==)
    username: ENC(OtQF9Fh4EAn4q75vJt9psg96/DCimcpB)
    password: ENC(zkHwTGUzQQGwZJohtrHbvIkB2xIMGtm/)
  jpa:
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6792
      host: ENC(0l6KNqPy3QznPKX1Oc8KKoAqZ/uQu4jA)
      password: ENC(MfBuf4wr2l1e1d0eOZTNXHFmPk9RI52b)

  security:
    user:
      name: user
      password: 1234
    oauth2:
      client:
        android: ENX(NCPz/n4jm3VczyJgObnbqqFhbFfaIUbbRJ1rP670nORPz0mRWt/Iq8rRfJYQYxUntqGLgwl1By5VY39kXmbrtFU4WTCaXsbepoFEXaSPsXHOFkjUCXS/Xw==)
        apple: ENC(CkoD2RiKTi3g3RHBIL9NqampRjLP9hwIvHkbA/WeshF6ocbj+cLHUoq/lUhLlW3qfscl7PV+6ssJfN+Yl6mz4Frr8S5Q5HqFV8rQ4TGi9mVpYvV5+eyxdw==)

  elasticsearch:
    uri: http://awseb-awseb-clwnl48v6djo-1067213661.ap-northeast-2.elb.amazonaws.com
  ai-model:
    uri: http://ec2-43-203-108-7.ap-northeast-2.compute.amazonaws.com

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: celebit-sluv-mvp2

logging:
  level:
    org.hibernate.SQL: debug
#      com.zaxxer.hikari.HikariConfig: DEBUG
#      com.zaxxer.hikari.HikariDataSource: DEBUG

jwt:
  header: Authorization
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
  expiration-seconds: 31536000000
  type: Bearer

apple:
  #  nonce: 1
  clientId: com.sluv.celebit
  openKey: https://appleid.apple.com/auth/keys
  iss: https://appleid.apple.com

aws:
  s3:
    accessKey: AKIA5R23H6YS5ZD6OOCH
    secretKey: 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
    region: ap-northeast-2
    bucketName: elasticbeanstalk-ap-northeast-2-931662394917
    baseUrl: asset

discord:
  webhook:
    signup: ENC(wvKiKsCnlSc/IdbNW5ymu7APd3STZiZFGe7Aogn6PJjpj22YO+HNxVWLetTJt6+r/7ShZ/B5SRJLHP/A9Vfpmk2R7mai7Ypa3SlPvoECUSv8Bg+KawlFdjjS7y6hU6aldCc735WhbJSDUwE3aZ8IjKi2phagn3xuldMlhnIZ+4A1WnpozCSiWw==)
    withdraw: ENC(eWZMiQS8KNxR8gPGkXuazXxyamoke+4+XdFz1KT2Kn3gQHalD66182TOj8pIEpvwSkb7Eimqhq5nY2lg1xlN9s5Uy9Re1DONDp6IDbjwCLkVpTF8XYO8uqJv1qL2kNHXie2ZFQGSpTK5CzRNWZtyzM5HAHvVxVJUdCuDxQNy/waVeE1EIHbskw==)
