spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(umIPYOdrigHivpZxQUaBn+1360z+xy13Hb4gHcoDY16JKXGxOF2jx4F+KkoFv9RKiIu7nXxn7tv/PoUCRVEYxqf96mTuqV007F1N8C45mpzyBg+tCBbRyNW66k7k4E0o)
    username: ENC(gh46WFclECYl96UilXt8Lw==)
    password: ENC(2HaAZ8j7cAaYFkIcemnUifSA0UAtPFLt)
  jpa:
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
    oauth2:
      client:
        android: ${SECURITY_OAUTH2_CLIENT_ANDROID}
        apple: ${SECURITY_OAUTH2_CLIENT_APPLE}

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  expiration-seconds: ${JWT_EXPIRATION_SECONDS}
  type: Bearer

apple:
  #  nonce: 1
  clientId: ${APPLE_CLIENT_ID}
  openKey: https://appleid.apple.com/auth/keys
  iss: https://appleid.apple.com

aws:
  s3:
    accessKey: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
    region: ap-northeast-2
    bucketName: ${AWS_S3_BUCKET_NAME}
    baseUrl: ${AWS_S3_BASE_URL}